export const COMENT_CREATE_FAIL = "COMENT_CREATE_FAIL";
export const COMENT_CREATE_REQUEST = "COMENT_CREATE_REQUEST";
export const COMENT_CREATE_SUCCESS = "COMENT_CREATE_SUCCESS";
export const COMENT_CREATE_REST = "COMENT_CREATE_REST";

export const GET_COMENTS_FAIL = "GET_COMENTS_FAIL";
export const GET_COMENTS_REQUEST = "GET_COMENTS_REQUEST";
export const GET_COMENTS_SUCCESS = "GET_COMENTS_SUCCESS";
export const GET_COMENTS_REST = "GET_COMENTS_REST";
