export const UPLOAD_DRAWING_REQUEST = "UPLOAD_DRAWING_REQUEST";
export const UPLOAD_DRAWING_SUCCESS = "UPLOAD_DRAWING_SUCCESS";
export const UPLOAD_DRAWING_FAIL = "UPLOAD_DRAWING_FAIL";
export const UPLOAD_DRAWING_RESET = "UPLOAD_DRAWING_RESET";

export const GET_DRAWING_USER_ID_REQUEST = "GET_DRAWING_USER_ID_REQUEST";
export const GET_DRAWING_USER_ID_SUCCESS = "GET_DRAWING_USER_ID_SUCCESS";
export const GET_DRAWING_USER_ID_FAIL = "GET_DRAWING_USER_ID_FAIL";
export const GET_DRAWING_USER_ID_RESET = "GET_DRAWING_USER_ID_RESET";

export const GET_DRAWING_BY_ID_REQUEST = "GET_DRAWING_BY_ID_REQUEST";
export const GET_DRAWING_BY_ID_SUCCESS = "GET_DRAWING_BY_ID_SUCCESS";
export const GET_DRAWING_BY_ID_FAIL = "GET_DRAWING_BY_ID_FAIL";
export const GET_DRAWING_BY_ID_RESET = "GET_DRAWING_BY_ID_RESET";
