export const UPLOAD_DRAWING_REQUEST = "UPLOAD_DRAWING_REQUEST";
export const UPLOAD_DRAWING_SUCCESS = "UPLOAD_DRAWING_SUCCESS";
export const UPLOAD_DRAWING_FAIL = "UPLOAD_DRAWING_FAIL";
export const UPLOAD_DRAWING_RESET = "UPLOAD_DRAWING_RESET";
