export const TEST_CREATE_FAIL = "TEST_CREATE_FAIL";
export const TEST_CREATE_REQUEST = "TEST_CREATE_REQUEST";
export const TEST_CREATE_SUCCESS = "TEST_CREATE_SUCCESS";
export const TEST_CREATE_REST = "TEST_CREATE_REST";

export const GET_TESTS_FAIL = "GET_TESTS_FAIL";
export const GET_TESTS_REQUEST = "GET_TESTS_REQUEST";
export const GET_TESTS_SUCCESS = "GET_TESTS_SUCCESS";
export const GET_TESTS_REST = "GET_TESTS_REST";
