export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST ";
export const USER_REGISTER_SUSSCESS = "USER_REGISTER_SUSSCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";

export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST ";
export const USER_SIGNIN_SUSSCESS = "USER_SIGNIN_SUSSCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
export const USER_SIGNIN_RESET = "USER_SIGNIN_RESET";
