export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST ";
export const USER_REGISTER_SUSSCESS = "USER_REGISTER_SUSSCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";

export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST ";
export const USER_SIGNIN_SUSSCESS = "USER_SIGNIN_SUSSCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
export const USER_SIGNIN_RESET = "USER_SIGNIN_RESET";

export const GET_USERS_REQUEST = "GET_USERS_REQUEST ";
export const GET_USERS_SUSSCESS = "GET_USERS_SUSSCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";
export const GET_USERS_RESET = "GET_USERS_RESET";
